Confirm that current multiprocessing error is not due to pickling class method
Took the log_probability method out of ErrorBudget class, still get the
ValueError: "Pool not running," with the same traceback.